name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql-app:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: practice
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List running containers
        run: docker ps
      - name: Wait for MySQL to be ready
        run: |
          until docker exec $(docker ps -q --filter ancestor=mysql-app) mysqladmin --user=root --password=admin --host=mysql-app --port=3306 ping --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!""

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Build Docker Image
        run: docker build -t my-spring-boot-app .

      - name: Run Docker Compose
        run: docker-compose up -d --build
